### ISSUE TITLE
Add support for querying .onion hostnames

### ISSUE THREAD

**Issue by phantomcraft** [bfix/Tor-DNS#12] opened 2020-04-29 09:26 UTC
When I try to query an .onion domain I get the following error:

```
root@localhost:/dev/shm/Tor-DNS# ./tor-dns -s "127.0.0.1:9050" -v
[Query:c622] cwu7eglxcabwttzf.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:c622] cwu7eglxcabwttzf.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:c622] cwu7eglxcabwttzf.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:c622] cwu7eglxcabwttzf.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:bcf3] dhosting4xxoydyaivckq7tsmtgi4wfs3flpeyitekkmqwu4v4r46syd.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:bcf3] dhosting4xxoydyaivckq7tsmtgi4wfs3flpeyitekkmqwu4v4r46syd.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:bcf3] dhosting4xxoydyaivckq7tsmtgi4wfs3flpeyitekkmqwu4v4r46syd.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
[Query:bcf3] dhosting4xxoydyaivckq7tsmtgi4wfs3flpeyitekkmqwu4v4r46syd.onion
[Tor-DNS] recovered: runtime error: slice bounds out of range [:259] with capacity 128
```

```
user@localhost:/home/user# host cwu7eglxcabwttzf.onion
;; connection timed out; no servers could be reached

user@localhost:/home/user# host dhosting4xxoydyaivckq7tsmtgi4wfs3flpeyitekkmqwu4v4r46syd.onion
;; connection timed out; no servers could be reached
```

**Comment by mtrojnar** [comment] 2020-05-03 08:18
Tor connects hidden services via names, and not IP addresses.  There is an `AutomapHostsOnResolve` torrc option that emulates the behavior you expect by assigning temporary virtual IP addresses: https://2019.www.torproject.org/docs/tor-manual.html.en#AutomapHostsOnResolve
Have you enabled it?

**Comment by phantomcraft** [comment] 2020-05-03 09:43
Yes, I enabled it.

```
VirtualAddrNetworkIPv4 10.192.0.0/10
VirtualAddrNetworkIPv6 [fe80::]/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .onion,.exit
```

That's why a virtual address is necessary to access .onion sites through a transparent proxy.

**Comment by mtrojnar** [comment] 2020-05-03 19:17
@phantomcraft Your explanation helped me reproduce your issue.  Thank you.
I investigated the error and it was caused by missing support for resolving IPv6 addresses.  I submitted a PR.

**Comment by phantomcraft** [comment] 2020-05-03 19:21
See my comment on your pull request.

It doesn't work well yet.

It seems that Tor SOCKS5 only returns one address. The only way to implement A+AAAA+.onion queries would be rewriting the program to use Tor control port/socket as this project do: https://github.com/schoentoon/tordns

The disadvantage would be the fact of providing a password for Tor control port when firing it up.

**Closed as completed** 2020-05-03 22:03 UTC

**Comment by phantomcraft** [comment] 2020-05-05 10:49
I tested the latest commit, works partially.

When an .onion domain is queried with Tor's DNSPort option, both IPv4/6 are showed:

```
user@localhost:/dev/shm$ host -p 9053 blahblahblahblah.onion
blahblahblahblah.onion has address 10.197.122.217
blahblahblahblah.onion has IPv6 address fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
Host blahblahblahblah.onion not found: 4(NOTIMP)
```

When using Tor-DNS, only IPv6 address is showed:

```
user@localhost:/dev/shm/Tor-DNS$ ./tor-dns -p "[::]:1053" -v
[Query:da8:1] blahblahblahblah.onion
[Response:da8] fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
[Query:668d:28] blahblahblahblah.onion
[Response:668d] fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
[Query:c017:15] blahblahblahblah.onion
[Response:c017] fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed

user@localhost:/dev/shm$ host -p 1053 blahblahblahblah.onion
blahblahblahblah.onion has IPv6 address fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
blahblahblahblah.onion has IPv6 address fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
blahblahblahblah.onion has IPv6 address fe8f:ef5e:c14b:bd4d:c280:2bd4:83ed:90ed
```

My Tor configuration is OK:

**[...]
VirtualAddrNetworkIPv4 10.192.0.0/10
VirtualAddrNetworkIPv6 [fe80::]/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .onion,.exit
[...]
DNSPort 127.0.0.1:9053 IPv6Traffic PreferIPv6
DNSPort [::1]:9053 IPv6Traffic PreferIPv6
[...]**

**Comment by mtrojnar** [comment] 2020-05-05 11:07
This is expected.  The Tor's DNSPort option does **not** resolve IP addresses over SOCKS, so it may return more than one IP address.  SOCKS only returns one IP address, and there is nothing we can do about it.

Also see: https://github.com/torproject/tor/pull/1854

**Comment by phantomcraft** [comment] 2020-05-07 03:13
@mtrojnar @bfix 

Please, take a look at this ticket I opened on Tor wiki: https://trac.torproject.org/projects/tor/ticket/34135#ticket

If they consider to implement this, it can be the way to resolve this issue (and that another with AAAA queries).

**Comment by mtrojnar** [comment] 2020-05-07 03:57
The way you worded your ticket makes it really hard to understand what you actually proposed. Consider separating your description of the requested feature from your rationale/alternatives. Bullet points may be useful.

Anyway, the idea is good (if I understood it correctly).
